### PR TITLE
Refactoring/error prone parsing

### PR DESCRIPTION
**Pull request by yoyostile**

### CODE REVIEW

**Comment by tobischo** [comment]
Hi, thanks for the pull request.
I will take a look as soon as I have some time.
I do not like adding active support as a dependency though (the first thing I noticed)

**Comment by yoyostile** [comment]
Oh, I'm sorry, this PR is not meant to be merged with your project. I accidentally checked the wrong repo.

**Comment by tobischo** [comment]
Well, improvements are certainly welcome :)

**Comment by yoyostile** [comment]
I've changed the API to match our [CMXL](https://github.com/railslove/cmxl)-Gem. I'm not sure if this interesting for this project - but I guess there are certainly some improvements regarding xml handling with nokogiri. Have a look at [the diff](https://github.com/Barzahlen/camt_parser/compare/master...railslove:master)! 👍 :)

**Comment by tobischo** [comment]
Thanks, I will take a look :)
I am still not happy with the activesupport dependency, since you are only using `try` in a single place (`Statement#identification`)

**Comment by tobischo** [comment]
After having a closer look:
- Using `try` in a single place is not really useful if that entails an additional dependency
- You added new code but did not add tests for the new classes in all cases. You only made sure existing tests work. For example: I couldn't find any tests for `AccountBalance`.
- Your last test fix should have been a fix in the code: in my opinion amounts of money should never be Float but always BigDecimal to avoid `weird` bugs in number precision.

I appreciate the hint and the link to your improvements. With the current state however, it would be way to much effort for me to get your changes included and have a version which I would be willing to release.

If you want specific features or refactorings added, you can open another (intended) pull request.
I want to see tests for the code though and I would prefer to avoid unnecessary dependencies.

**Comment by yoyostile** [comment]
Sure, as I've mentioned before this is just a quick fork for internal usage and is not intended to be a proper release. I'll fix and clean up some things, as soon as I have spare time for that. 
Thanks for your input.

**Comment by tobischo** [comment]
I understand that :)
If you are certain, that none of your changes will be needed anywhere in production, it is totally fine to not follow up on this.
Unfortunately it happens rather often that something, that was just intended as a demo, ends up being used in production in an unaltered form.

Your changes are good though and improve the readability greatly. Also they extend the functionality by stuff we did not implement, because we did not need it yet - other people might need it though.
It would be a shame to throw it away.

**Comment by yoyostile** [comment]
Jfyi, for now I removed the active_support dependency, refactored specs and added some more tests. Still, there are lots of `alias_methods` which are needed to gain compatibility with our CMXL gem and are presumably not of interest for anyone. :)

**Pull request closed without merging**
